<a href="https://colab.research.google.com/github/BoYeonJang/ICT-AI-education/blob/main/(8%EC%9B%94%205%EC%9D%BC)%20%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%20%EA%B0%9C%EB%85%90%EA%B3%BC%20%EB%94%A5%EB%9F%AC%EB%8B%9D%20%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0/Numpy_%EC%8B%A4%EC%A0%84%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### 버전확인

In [2]:
print(np.__version__)

1.21.6


### 사이즈가 10인 null 벡터

In [3]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 인덱스 4번의 값을 1로 변경

In [4]:
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


`z = np.arange(10, 50)`
- 거꾸로

In [5]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 3x3 행렬을 0에서 8까지

In [7]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### non-zero [1,2,0,0,4,0]

In [8]:
lit = [1,2,0,0,4,0]
np.nonzero(lit)

(array([0, 1, 4]),)

In [9]:
import pandas as pd

data = {
    'year': [2019, 2020, 2021],
    'GDP rate': [2.8, 3.1, 3.0],
    'GDP': ['1.637M', '1.73M', '1.83M']
}

In [10]:
df = pd.DataFrame(data, index = data['year'])

In [12]:
df

year  GDP rate     GDP
2019  2019       2.8  1.637M
2020  2020       3.1   1.73M
2021  2021       3.0   1.83M

### 혈액형

- blood = ['A형', 'B형', 'O형', 'AB형']

### 혈액형 통계자료

- st = [34.2, 27.1, 26.7, 11.5]

혈액형 통계 수치를 이용하여 혈액형(blood) 인덱스를 가지는 시리즈 생성하기

In [14]:
blood = ['A형', 'B형', 'O형', 'AB형']
st = [34.2, 27.1, 26.7, 11.5]

In [15]:
result = pd.Series(st, index = blood)
print(result)

A형     34.2
B형     27.1
O형     26.7
AB형    11.5
dtype: float64


### DataFrame으로 변경

In [19]:
df2 = pd.DataFrame(st, index = blood)
df2

0
A형   34.2
B형   27.1
O형   26.7
AB형  11.5

In [21]:
result = {
    'blood': ['A형', 'B형', 'O형', 'AB형'],
    'st': [34.2, 27.1, 26.7, 11.5]
}

df3 = pd.DataFrame(result, index = result['blood'])
df3

blood    st
A형     A형  34.2
B형     B형  27.1
O형     O형  26.7
AB형   AB형  11.5